name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out!
        uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
