name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checking out!
        uses: actions/checkout@v1
      
      - 
        name: hello-world-action
        uses: ./.github/actions/hello-world
        
      - 
        name: joke-action
        uses: ./.github/actions/joke-action
        id: jokes
      
      - 
        name: issue-maker-action
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          joke: ${{ steps.jokes.outputs.joke-output }}
      
      
      
      
