name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out!
        uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "hola 1"
          second-greeting: "hola 2"
          third-greeting: "hola 3"
          
